[project]
name = "fc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "panda>=0.3.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
